name: loadbalancer
namespace: loadbalancer
namespaceLabels:
  space: service
space: service
description: MetalLB loadbalancer.

apps:
  - name: loadbalancer
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.6
      chart: loadbalancer
      valuesFile: "loadbalancer.yaml"
