name: loadbalancer
namespace: loadbalancer
space: service
description: MetalLB loadbalancer.

project:
  name: loadbalancer
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: loadbalancer
    source:
      repoURL: "https://github.com/distributed-technologies/services-loadbalancer.git"
      targetRevision: v0.1.5
      path: chart
      valuesFile: "loadbalancer.yaml"
