## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint.md
# Configuration for the ct helm cart linting
remote: origin
target-branch: main
chart-dirs:
  - "."
chart-repos:
  - helmcharts=https://distributed-technologies.github.io/helm-charts/
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
