kube-prometheus-stack:
  grafana:
    enabled: false
  {{- if .Values.registry }}
  alertmanager: 
    alertmanagerSpec:
      image: 
        repository: {{ .Values.registry }}/prometheus/alertmanager
  prometheusOperator:
    admissionWebhooks: 
      patch:
        image: 
          repository: {{ .Values.registry }}/ingress-nginx/kube-webhook-certgen
    image: 
      repository: {{ .Values.registry }}/prometheus-operator/prometheus-operator 
    prometheusConfigReloaderImage: 
      repository: {{ .Values.registry }}/prometheus-operator/prometheus-config-reloader
  {{- end }}

  prometheus: 
    prometheusSpec: 
      replicas: 3
  {{- if .Values.registry }}
      image: 
        repository: {{ .Values.registry }}/prometheus/prometheus

  kube-state-metrics: 
    image:
      repository: {{ .Values.registry }}/kube-state-metrics/kube-state-metrics

  prometheus-node-exporter:
    image:
      repository: {{ .Values.registry }}/prometheus/node-exporter
  {{- end }}
