# This values is if you want to use paths instead of subdomains.
ingressDomain: jesperdev.garagen

networking:
  enabled: true

  ingress:
    enabled: true

  cert-manager:
    enabled: false

  cert-manager-issuer: 
    enabled: false

tooling: 
  enabled: true

  argowf:
    enabled: false

  argo-events:
    enabled: false

  harbor:
    enabled: false

  vault:
    enabled: false

monitoring:
  enabled: true

  prometheus:
    enabled: true

  thanos:
    enabled: false
  
  grafana:
    enabled: true
  
  loki:
    enabled: true

  jaeger-operator:
    enabled: false

rook-ceph: 
  enabled: true

  rook:
    enabled: true

  ceph: 
    enabled: true

loadbalancer: 
  enabled: true

  loadbalancer: 
    enabled: true

cache: 
  enabled: false
  
  cache:
    enabled: false

kafka: 
  enabled: false

  kafka: 
    enabled: false

nifi:
  enabled: false

  nifi:
    enabled: false

  influxdb:
    enabled: false

