# This values is if you want to use paths instead of subdomains.
ingressDomain: dev.garagen
clusterNetworking: 
  ipRangeStart: 192.168.1.40
  # ipRangeStop is both the ipRangeStop but also the ingress loadBalancerIP
  ipRangeStop: 192.168.1.49

registry: harbor.sc.garagen/yggdrasil

applications: 
  - ingress
#  - cert-manager
#  - cert-manager-issuer 
#  - argowf
#  - argo-events
#  - harbor
#  - vault
  - prometheus
#  - thanos
  - grafana
#  - loki
#  - jaeger-operator
  - rook
  - ceph
  - loadbalancer
#  - cache
#  - kafka
#  - nifi
#  - influxdb
